name: Unitary Test

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Test
      run: python3 -m unittest MyClass.py 

    - name: Lint test
      run: |
        python3 -m pip install pylint
        pylint --exit-zero MyClass.py

    - name: Build Docker image
      run: docker build -t test-python .